# 팔머 펭귄 예측 문제 (분류)

- 1. 데이터 불러오기
- 2. 데이터 분리
- 3. 모델 학습
- 4. 예측
- 5. 결과

In [205]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier # 분류 문제니까 얘 들고와야 함
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

# 1st
df = pd.read_csv('data/penguins.csv')
df.head()

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,4,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,5,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [206]:
df['species'].value_counts() # 답안지 구성 확인

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [207]:
# 2nd
# df = pd.get_dummies(df, columns=['species', 'sex', 'island'], drop_first=True) # 강제로 타입 변환시킴, bool로 0, 1 int로 변환되니까
df.head()

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,4,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,5,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [208]:
# 3rd
df = df.fillna(0) # 원래는 이러면 안 되고 중위값이나 평균값 넣어야 함
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rowid              344 non-null    int64
 1   species            344 non-null    object
 2   island             344 non-null    object
 3   bill_length_mm     344 non-null    float64
 4   bill_depth_mm      344 non-null    float64
 5   flipper_length_mm  344 non-null    float64
 6   body_mass_g        344 non-null    float64
 7   sex                344 non-null    object
 8   year               344 non-null    int64
dtypes: float64(4), int64(2), object(3)
memory usage: 24.3+ KB

In [209]:
X = df.drop(['species', 'sex', 'island', 'rowid'], axis=1)
y = df["species"]
print(X.shape, y.shape)

(344, 5) (344,)

In [210]:
#---------------knn으로 학습
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [211]:
knn = KNeighborsClassifier(n_neighbors=5) # n_neighbors 바꿔가면서 결과 확인해서 좋은 거 찾아보기
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [212]:
lr = LogisticRegression(max_iter=3000)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=3000)

In [213]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [214]:
knn_y_pred = knn.predict(X_test)
lr_y_pred = lr.predict(X_test)
gnb_y_pred = gnb.predict(X_test)

In [ ]:
print(accuracy_score(knn_y_pred, y_test))
print(accuracy_score(lr_y_pred, y_test)) # 선형이 더 좋을 수도
print(accuracy_score(gnb_y_pred, y_test))
# 분류는 맞는 걸 맞다고 한 것이랑 틀린 걸 틀리다고 하는 게 중요

0.7558139534883721
0.9767441860465116
0.9767441860465116